// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClassName int32

const (
	ClassName_class1 ClassName = 0
	ClassName_class2 ClassName = 1
	ClassName_class3 ClassName = 2
)

var ClassName_name = map[int32]string{
	0: "class1",
	1: "class2",
	2: "class3",
}

var ClassName_value = map[string]int32{
	"class1": 0,
	"class2": 1,
	"class3": 2,
}

func (x ClassName) String() string {
	return proto.EnumName(ClassName_name, int32(x))
}

func (ClassName) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

type Student struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32     `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Address              string    `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Cn                   ClassName `protobuf:"varint,4,opt,name=cn,proto3,enum=main.ClassName" json:"cn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

func (m *Student) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Student.Unmarshal(m, b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Student.Marshal(b, m, deterministic)
}
func (m *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(m, src)
}
func (m *Student) XXX_Size() int {
	return xxx_messageInfo_Student.Size(m)
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Student) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Student) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Student) GetCn() ClassName {
	if m != nil {
		return m.Cn
	}
	return ClassName_class1
}

type Students struct {
	Person               []*Student `protobuf:"bytes,1,rep,name=person,proto3" json:"person,omitempty"`
	School               string     `protobuf:"bytes,2,opt,name=school,proto3" json:"school,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Students) Reset()         { *m = Students{} }
func (m *Students) String() string { return proto.CompactTextString(m) }
func (*Students) ProtoMessage()    {}
func (*Students) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1}
}

func (m *Students) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Students.Unmarshal(m, b)
}
func (m *Students) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Students.Marshal(b, m, deterministic)
}
func (m *Students) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Students.Merge(m, src)
}
func (m *Students) XXX_Size() int {
	return xxx_messageInfo_Students.Size(m)
}
func (m *Students) XXX_DiscardUnknown() {
	xxx_messageInfo_Students.DiscardUnknown(m)
}

var xxx_messageInfo_Students proto.InternalMessageInfo

func (m *Students) GetPerson() []*Student {
	if m != nil {
		return m.Person
	}
	return nil
}

func (m *Students) GetSchool() string {
	if m != nil {
		return m.School
	}
	return ""
}

func init() {
	proto.RegisterEnum("main.ClassName", ClassName_name, ClassName_value)
	proto.RegisterType((*Student)(nil), "main.Student")
	proto.RegisterType((*Students)(nil), "main.Students")
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6) }

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0xcd, 0x4e, 0xc5, 0x20,
	0x10, 0x85, 0xa5, 0xad, 0x5c, 0x3b, 0xe6, 0x2a, 0x99, 0x85, 0x61, 0x27, 0xb9, 0x89, 0x09, 0x71,
	0x51, 0x63, 0xfb, 0x08, 0xae, 0xdc, 0xb8, 0xc0, 0x27, 0x40, 0x3a, 0xf1, 0x27, 0x05, 0x9a, 0x52,
	0x13, 0x1f, 0xdf, 0x14, 0xb1, 0xbb, 0xef, 0xcb, 0x81, 0x33, 0x33, 0x70, 0xa4, 0x1f, 0xeb, 0xe7,
	0x89, 0xba, 0x79, 0x89, 0x6b, 0xc4, 0xc6, 0xdb, 0xcf, 0x70, 0xfa, 0x82, 0xc3, 0xeb, 0xfa, 0x3d,
	0x52, 0x58, 0x11, 0xa1, 0x09, 0xd6, 0x93, 0x64, 0x8a, 0xe9, 0xd6, 0x64, 0x46, 0x01, 0xb5, 0x7d,
	0x27, 0x59, 0x29, 0xa6, 0xcf, 0xcd, 0x86, 0x28, 0xe1, 0x60, 0xc7, 0x71, 0xa1, 0x94, 0x64, 0x9d,
	0x1f, 0xfe, 0x2b, 0xde, 0x42, 0xe5, 0x82, 0x6c, 0x14, 0xd3, 0x57, 0xfd, 0x75, 0xb7, 0xb5, 0x77,
	0x4f, 0x93, 0x4d, 0xe9, 0xc5, 0x7a, 0x32, 0x95, 0x0b, 0xa7, 0x67, 0xb8, 0x28, 0xb3, 0x12, 0xde,
	0x01, 0x9f, 0x69, 0x49, 0x31, 0x48, 0xa6, 0x6a, 0x7d, 0xd9, 0x1f, 0xff, 0x3e, 0x94, 0xdc, 0x94,
	0x10, 0x6f, 0x80, 0x27, 0xf7, 0x11, 0xe3, 0x94, 0x57, 0x68, 0x4d, 0xb1, 0xfb, 0x07, 0x68, 0xf7,
	0x6e, 0x04, 0xe0, 0x6e, 0x93, 0x47, 0x71, 0xb6, 0x73, 0x2f, 0xd8, 0xce, 0x83, 0xa8, 0xde, 0x78,
	0x3e, 0x7a, 0xf8, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x33, 0xcb, 0xd3, 0x05, 0x01, 0x00, 0x00,
}
